### ISSUE TITLE
Can this tools generate a PDF or svg file?

### ISSUE THREAD

**Issue by LanLBio** [althonos/rich-msa#2]
Hi,
It is such an amazing tools! I love this pattern to show the msa results. 
But I am wondering if it can generante a PDF file that contain the output show in the terminal?

Lan

**Comment by althonos** [comment]
Hi Lan!

The `RichAlignment` is a `rich` renderable object, and `rich` implements exporting to SVG. You can get a result Simply print to a console in record mode and use the [`Console.export_svg`](https://rich.readthedocs.io/en/stable/reference/console.html#rich.console.Console.export_svg) method to get an SVG representation.

For instance:
```python
import Bio.AlignIO
import rich
from rich_msa import RichAlignment

msa = Bio.AlignIO.read("tests/data/swissprot-halorhodopsin.muscle.afa", "fasta")
viewer = RichAlignment(
    names=[record.id for record in msa],
    sequences=[str(record.seq) for record in msa],
)

console = rich.console.Console(record=True, quiet=True)
console.print(viewer)

with open("example.svg", "w") as f:
    f.write(console.export_svg())
```

This will write a SVG file named `example.svg` the following content: 
![example](https://user-images.githubusercontent.com/8660647/171660255-83c102c2-8cae-43a9-8fc6-cae3bc74036b.svg)
